---
version: "3.8"

services:
  gateway:
    image: envoyproxy/envoy:v1.24.0
    ports:
      - ${GATEWAY_PORT-8000}:8080
    volumes:
      - ./app/platform/gateway/envoy/env/local/envoy.yaml:/etc/envoy/envoy.yaml
      - ./bin/proxy-wasm-google-metadata-identity-token.wasm:/etc/envoy/proxy-wasm-google-metadata-identity-token.wasm
      - ./bin/proxy-wasm-cloud-logging-trace-context.wasm:/etc/envoy/proxy-wasm-cloud-logging-trace-context.wasm
      - ./bin/proxy-wasm-http-header-rename.wasm:/etc/envoy/proxy-wasm-http-header-rename.wasm
    command: /docker-entrypoint.sh envoy -c /etc/envoy/envoy.yaml --log-format '%L%m%d %T.%e %t envoy/%@] [%t][%n]%v' --log-format-escaped

  customer-graph:
    image: ghcr.io/apollographql/router:v1.15.1
    volumes:
      - .:/go/src/github.com/kauche/kauche-microservices-example:cached
    working_dir: /go/src/github.com/kauche/kauche-microservices-example
    command: --config ./app/platform/customer-graph/router.yaml --supergraph ./api/platform/customer/graphql/schema.graphqls --anonymous-telemetry-disabled

  commerce:
    image: golang:1.20.4-bullseye
    volumes:
      - .:/go/src/github.com/kauche/kauche-microservices-example:cached
      - go-pkg-mod:/go/pkg/mod:cached
    working_dir: /go/src/github.com/kauche/kauche-microservices-example
    command: go run ./app/services/commerce

  commerce-graph:
    image: golang:1.20.4-bullseye
    volumes:
      - .:/go/src/github.com/kauche/kauche-microservices-example:cached
      - go-pkg-mod:/go/pkg/mod:cached
    working_dir: /go/src/github.com/kauche/kauche-microservices-example
    command: go run ./app/services/commerce-graph
    environment:
      COMMERCE_GRPC_ADDR: commerce:8000

  social-graph:
    image: golang:1.20.4-bullseye
    volumes:
      - .:/go/src/github.com/kauche/kauche-microservices-example:cached
      - go-pkg-mod:/go/pkg/mod:cached
    working_dir: /go/src/github.com/kauche/kauche-microservices-example
    command: go run ./app/services/social-graph

volumes:
  go-pkg-mod:
