// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Comment struct {
	ID       string    `json:"id"`
	Text     string    `json:"text"`
	Customer *Customer `json:"customer"`
}

type Customer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID       string     `json:"id"`
	Comments []*Comment `json:"comments"`
}

func (Product) IsEntity() {}
