//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.8.2'.
//
package com.kauche.api.platform.customer.graphql.type

import com.apollographql.apollo3.api.ObjectType

public class Comment {
  public companion object {
    public val type: ObjectType = ObjectType.Builder(name = "Comment").build()
  }
}
